const AUTHORITIES = [
{n:"Algeria",a:"Agence Nationale des Activités Minières (ANAM)",au:"anam.dz [verify]",g:"Office National de la Recherche Géologique et Minière (ORGM)",gu:"orgm.dz [verify]"},
{n:"Angola",a:"Ministério dos Recursos Minerais, Petróleo e Gás (MIREMPET)",au:"mirempet.gov.ao [verify]",g:"Instituto Geológico de Angola (IGEO)",gu:"igeo.gov.ao [verify]"},
{n:"Benin",a:"Ministère de l'Eau et des Mines",au:"eaumines.gouv.bj [verify]",g:"Office Béninois de Recherches Géologiques et Minières (OBRGM)",gu:"[verify]"},
{n:"Botswana",a:"Ministry of Minerals and Energy · Department of Mines",au:"mme.gov.bw",g:"Botswana Geoscience Institute (BGI)",gu:"bgi.org.bw"},
{n:"Burkina Faso",a:"Ministère de l'Énergie, des Mines et des Carrières",au:"memc.gov.bf [verify]",g:"Bureau des Mines et de la Géologie du Burkina (BUMIGEB)",gu:"bumigeb.bf [verify]"},
{n:"Burundi",a:"Ministère de l'Hydraulique, de l'Énergie et des Mines · Office Burundais des Mines et Carrières (OBM)",au:"[verify]",g:"OBM (geology under same ministry)",gu:"[verify]"},
{n:"Cabo Verde",a:"Direção Nacional da Indústria, Comércio e Energia",au:"dgei.gov.cv [verify]",g:"No dedicated geological survey — data via ministry",gu:"-"},
{n:"Cameroon",a:"Ministère des Mines, de l'Industrie et du Développement Technologique (MINMIDT)",au:"minmidt.cm [verify]",g:"Société Nationale des Mines (SONAMINES)",gu:"sonamines.cm [verify]"},
{n:"Central African Republic",a:"Ministère des Mines et de la Géologie",au:"[verify]",g:"Direction Générale de la Géologie",gu:"[verify]"},
{n:"Chad",a:"Ministère des Mines et de la Géologie",au:"[verify]",g:"Direction de la Recherche Géologique et Minière",gu:"[verify]"},
{n:"Comoros",a:"Ministère de l'Économie / Direction Générale des Mines",au:"[verify]",g:"No dedicated survey",gu:"-"},
{n:"Congo (Rep.)",a:"Ministère des Mines et de la Géologie",au:"mines.gouv.cg [verify]",g:"Bureau de Recherches Géologiques et Minières du Congo",gu:"[verify]"},
{n:"Côte d'Ivoire",a:"Ministère des Mines, du Pétrole et de l'Énergie",au:"energie.gouv.ci [verify]",g:"Société pour le Développement Minier de la Côte d'Ivoire (SODEMI)",gu:"sodemi.ci [verify]"},
{n:"DR Congo",a:"Ministère des Mines · CAMI (Cadastre Minier)",au:"mines-rdc.cd  ·  cami.cd  (online cadastre)",g:"Service Géologique National du Congo (SGN-C)",gu:"[verify]"},
{n:"Djibouti",a:"Ministère de l'Énergie chargé des Ressources Naturelles",au:"[verify]",g:"Office of Geology under the ministry",gu:"[verify]"},
{n:"Egypt",a:"Egyptian Mineral Resources Authority (EMRA)",au:"emra.gov.eg",g:"EMRA (same body handles geology)",gu:"emra.gov.eg"},
{n:"Equatorial Guinea",a:"Ministerio de Minas e Hidrocarburos",au:"[verify]",g:"Same ministry / national oil & mining company",gu:"[verify]"},
{n:"Eritrea",a:"Ministry of Energy and Mines · Department of Mines",au:"shabait.com [verify]",g:"Eritrean Institute of Technology - Earth Sciences",gu:"[verify]"},
{n:"Eswatini",a:"Ministry of Natural Resources and Energy · Department of Mines",au:"gov.sz [verify]",g:"Geological Survey and Mines Department",gu:"[verify]"},
{n:"Ethiopia",a:"Ministry of Mines",au:"mom.gov.et",g:"Geological Survey of Ethiopia (GSE)",gu:"gse.gov.et"},
{n:"Gabon",a:"Ministère des Mines",au:"mines.gouv.ga [verify]",g:"Société Équatoriale des Mines (SEM)",gu:"sem.ga [verify]"},
{n:"Gambia",a:"Ministry of Petroleum, Energy and Mineral Resources",au:"mopmr.gov.gm [verify]",g:"Department of Geology",gu:"[verify]"},
{n:"Ghana",a:"Ministry of Lands and Natural Resources · Minerals Commission",au:"mincom.gov.gh  ·  ghanacadastre.mincom.gov.gh (online cadastre)",g:"Ghana Geological Survey Authority (GGSA)",gu:"ggsa.gov.gh"},
{n:"Guinea",a:"Ministère des Mines et de la Géologie",au:"mines.gov.gn",g:"Centre de Promotion et de Développement Minier (CPDM)",gu:"[verify]"},
{n:"Guinea-Bissau",a:"Ministério dos Recursos Naturais e Energia",au:"[verify]",g:"Direção Geral da Geologia e Minas",gu:"[verify]"},
{n:"Kenya",a:"Ministry of Mining, Blue Economy and Maritime Affairs · State Department for Mining",au:"mining.go.ke  ·  onlinemining.mining.go.ke (cadastre)",g:"Geological Survey of Kenya (under ministry)",gu:"-"},
{n:"Lesotho",a:"Ministry of Natural Resources · Department of Mines",au:"gov.ls [verify]",g:"Department of Mines / Commissioner of Mines",gu:"[verify]"},
{n:"Liberia",a:"Ministry of Mines and Energy",au:"molme.gov.lr [verify]",g:"Liberia Geological Survey (LGS)",gu:"[verify]"},
{n:"Libya",a:"Ministry of Industry and Minerals",au:"[verify]",g:"Industrial Research Centre – Geological Department",gu:"irc.gov.ly [verify]"},
{n:"Madagascar",a:"Ministère des Mines et des Ressources Stratégiques",au:"mines.gov.mg [verify]",g:"Bureau du Cadastre Minier de Madagascar (BCMM)",gu:"bcmm.mg [verify]"},
{n:"Malawi",a:"Ministry of Mining",au:"mining.gov.mw [verify]",g:"Geological Survey Department of Malawi",gu:"gsd.gov.mw [verify]"},
{n:"Mali",a:"Ministère des Mines · Direction Nationale de la Géologie et des Mines (DNGM)",au:"dngm.gouv.ml [verify]",g:"DNGM",gu:"dngm.gouv.ml [verify]"},
{n:"Mauritania",a:"Ministère du Pétrole, des Mines et de l'Énergie",au:"petrole.gov.mr [verify]",g:"Office Mauritanien de Recherches Géologiques (OMRG)",gu:"omrg.mr [verify]"},
{n:"Mauritius",a:"Ministry of Energy and Public Utilities",au:"[verify]",g:"No commercial mining — quarrying only",gu:"-"},
{n:"Morocco",a:"Ministère de la Transition Énergétique et du Développement Durable · Direction des Mines",au:"mem.gov.ma [verify]",g:"Office National des Hydrocarbures et des Mines (ONHYM)",gu:"onhym.com"},
{n:"Mozambique",a:"Ministério dos Recursos Minerais e Energia (MIREME)",au:"mireme.gov.mz",g:"Instituto Nacional de Minas (INAMI) — cadastre",gu:"inami.gov.mz [verify]"},
{n:"Namibia",a:"Ministry of Mines and Energy",au:"mme.gov.na",g:"Geological Survey of Namibia (GSN)",gu:"mme.gov.na/directorates/geosurvey"},
{n:"Niger",a:"Ministère des Mines",au:"mines.gouv.ne [verify]",g:"Société du Patrimoine des Mines du Niger (SOPAMIN)",gu:"sopamin.ne [verify]"},
{n:"Nigeria",a:"Ministry of Solid Minerals Development · Mining Cadastre Office (MCO)",au:"minesandsteel.gov.ng  ·  portal.miningcadastre.gov.ng",g:"Nigerian Geological Survey Agency (NGSA)",gu:"ngsa.gov.ng"},
{n:"Rwanda",a:"Rwanda Mines, Petroleum and Gas Board (RMB)",au:"rmb.gov.rw",g:"RMB — geology under same board",gu:"rmb.gov.rw"},
{n:"São Tomé & Príncipe",a:"Ministério das Infraestruturas e Recursos Naturais",au:"[verify]",g:"No dedicated survey",gu:"-"},
{n:"Senegal",a:"Ministère des Mines et de la Géologie",au:"mines.gouv.sn [verify]",g:"Direction des Mines et de la Géologie",gu:"[verify]"},
{n:"Seychelles",a:"Ministry of Agriculture, Climate Change and Environment",au:"[verify]",g:"No mining",gu:"-"},
{n:"Sierra Leone",a:"Ministry of Mines and Mineral Resources · National Minerals Agency (NMA)",au:"nma.gov.sl",g:"NMA — geology under same agency",gu:"nma.gov.sl"},
{n:"Somalia",a:"Ministry of Petroleum and Mineral Resources",au:"mopmr.gov.so [verify]",g:"Geological Survey (nascent)",gu:"[verify]"},
{n:"South Africa",a:"Department of Mineral Resources and Energy (DMRE) · SAMRAD online cadastre",au:"dmre.gov.za  ·  samradonline.dmr.gov.za",g:"Council for Geoscience (CGS)",gu:"geoscience.org.za"},
{n:"South Sudan",a:"Ministry of Mining",au:"mom.gov.ss [verify]",g:"Directorate of Geological Survey",gu:"[verify]"},
{n:"Sudan",a:"Ministry of Minerals · Sudanese Mineral Resources Company (SMRC)",au:"[verify]",g:"Geological Research Authority of the Sudan (GRAS)",gu:"[verify]"},
{n:"Tanzania",a:"Ministry of Minerals · Mining Commission",au:"madini.go.tz  ·  portal.mmc.go.tz (cadastre)",g:"Geological Survey of Tanzania (GST)",gu:"gst.go.tz"},
{n:"Togo",a:"Ministère des Mines et de l'Énergie",au:"mines.gouv.tg [verify]",g:"Direction Générale des Mines et de la Géologie",gu:"[verify]"},
{n:"Tunisia",a:"Ministère de l'Industrie, de l'Énergie et des Mines",au:"industrie.gov.tn [verify]",g:"Office National des Mines (ONM)",gu:"onm.nat.tn [verify]"},
{n:"Uganda",a:"Ministry of Energy and Mineral Development · Directorate of Geological Survey and Mines (DGSM)",au:"energyandminerals.go.ug",g:"DGSM",gu:"dgsm.go.ug [verify]"},
{n:"Zambia",a:"Ministry of Mines and Minerals Development · Mining Cadastre",au:"mmmd.gov.zm  ·  portals.flexicadastre.com/zambia",g:"Geological Survey Department",gu:"[verify]"},
{n:"Zimbabwe",a:"Ministry of Mines and Mining Development",au:"mines.gov.zw [verify]",g:"Zimbabwe Geological Survey (under ministry)",gu:"[verify]"}
];
