/* ============================================================
   GOLDBELT AFRICA — SHARED DATA
   Districts are documented district/area centres from the public
   geological record (USGS MRDS, national surveys, BGS archive,
   filed technical reports). Centres are approximate by nature.
   Update LAST_UPDATED in index.html when districts are added.
   ============================================================ */

const DISTRICTS = [
/* ---------------- ZIMBABWE ---------------- */
{n:"Kadoma–Chakari District",c:"Zimbabwe",lat:-18.33,lng:29.91,t:"gold",note:"Midlands greenstone belt. Long history of reef and alluvial gold; heavily worked historic district."},
{n:"Kwekwe–Sherwood District",c:"Zimbabwe",lat:-18.93,lng:29.82,t:"gold",note:"Greenstone-hosted gold with extensive historic workings along the Great Dyke margin."},
{n:"Shamva District",c:"Zimbabwe",lat:-17.31,lng:31.57,t:"gold",note:"Harare–Bindura–Shamva greenstone belt. Documented reef gold and small-scale workings."},
{n:"Bindura District",c:"Zimbabwe",lat:-17.30,lng:31.33,t:"gold",note:"Northern limb of the Harare greenstone belt; gold with nickel occurrences nearby."},
{n:"Mazowe District",c:"Zimbabwe",lat:-17.52,lng:30.97,t:"gold",note:"Historic Mazowe valley gold; reef workings dating to the 1890s and older ancient workings."},
{n:"Penhalonga Valley",c:"Zimbabwe",lat:-18.89,lng:32.70,t:"gold",note:"Mutare greenstone belt. Historic alluvial and reef gold in the eastern highlands."},
{n:"Gwanda Belt",c:"Zimbabwe",lat:-20.94,lng:29.00,t:"gold",note:"Gwanda greenstone belt; dense cluster of historic gold workings."},
{n:"Filabusi Belt",c:"Zimbabwe",lat:-20.53,lng:29.28,t:"gold",note:"Filabusi greenstone belt; scores of recorded small gold mines."},
{n:"Shurugwi District",c:"Zimbabwe",lat:-19.67,lng:30.00,t:"gold",note:"Shurugwi greenstone belt gold with chrome seams on the adjacent Great Dyke."},
{n:"Chegutu District",c:"Zimbabwe",lat:-18.13,lng:30.14,t:"gold",note:"Gold workings between Chegutu and the Mupfure river drainages."},
{n:"Mount Darwin District",c:"Zimbabwe",lat:-16.78,lng:31.58,t:"gold",note:"Northern greenstone gold; strong artisanal activity in documented ground."},
{n:"Odzi District",c:"Zimbabwe",lat:-18.96,lng:32.38,t:"gold",note:"Odzi greenstone belt; historic reef gold west of Mutare."},
{n:"Great Dyke (Chrome & PGM)",c:"Zimbabwe",lat:-19.30,lng:29.90,t:"metal",note:"550 km layered intrusion; chrome and platinum seams, countless small workings."},
{n:"Bikita Pegmatite Field",c:"Zimbabwe",lat:-20.09,lng:31.42,t:"metal",note:"World-famous lithium–tantalum pegmatites; mined since the 1950s."},
/* ---------------- GHANA ---------------- */
{n:"Obuasi District",c:"Ghana",lat:6.20,lng:-1.67,t:"gold",note:"Ashanti belt. One of Africa's most productive gold districts for over a century."},
{n:"Tarkwa District",c:"Ghana",lat:5.30,lng:-1.99,t:"gold",note:"Tarkwaian conglomerate-hosted gold; major producing district."},
{n:"Prestea District",c:"Ghana",lat:5.43,lng:-2.14,t:"gold",note:"Deep historic underground gold along the Ashanti trend."},
{n:"Bogoso District",c:"Ghana",lat:5.57,lng:-2.03,t:"gold",note:"Shear-zone gold between Prestea and Tarkwa; long production record."},
{n:"Konongo District",c:"Ghana",lat:6.62,lng:-1.22,t:"gold",note:"Northeastern Ashanti belt gold; historic mines and modern reworking."},
{n:"Ahafo–Kenyasi District",c:"Ghana",lat:7.00,lng:-2.38,t:"gold",note:"Sefwi belt gold; one of Ghana's major modern producing districts."},
{n:"Damang District",c:"Ghana",lat:5.52,lng:-1.83,t:"gold",note:"Tarkwaian and hydrothermal gold north of Tarkwa."},
{n:"Bibiani Belt",c:"Ghana",lat:6.46,lng:-2.32,t:"gold",note:"Sefwi belt shear-zone gold; documented workings along the belt margin."},
{n:"Akwatia Diamond Field",c:"Ghana",lat:6.05,lng:-0.80,t:"gem",note:"Birim valley alluvial diamonds; hand-worked gravels for a century."},
/* ---------------- MALI ---------------- */
{n:"Kéniéba Window (Loulo)",c:"Mali",lat:12.94,lng:-11.32,t:"gold",note:"West Mali Birimian window; one of Africa's richest modern gold districts."},
{n:"Sadiola District",c:"Mali",lat:13.88,lng:-11.70,t:"gold",note:"Laterite and saprolite-hosted gold in the Kayes region."},
{n:"Morila District",c:"Mali",lat:11.68,lng:-7.42,t:"gold",note:"Southern Mali Birimian gold; famous high-grade discovery district."},
{n:"Kalana District",c:"Mali",lat:10.78,lng:-8.20,t:"gold",note:"Historic underground gold in the Yanfolila belt; strong artisanal presence."},
{n:"Syama Belt",c:"Mali",lat:10.90,lng:-6.02,t:"gold",note:"Southern Birimian greenstone gold near the Côte d'Ivoire border."},
{n:"Kangaba Corridor",c:"Mali",lat:11.93,lng:-8.42,t:"gold",note:"Upper Niger alluvial gold corridor; worked since the Mali Empire."},
/* ---------------- TANZANIA ---------------- */
{n:"Geita District",c:"Tanzania",lat:-2.87,lng:32.23,t:"gold",note:"Lake Victoria goldfields; greenstone-hosted gold south of the lake."},
{n:"Bulyanhulu–Kahama",c:"Tanzania",lat:-3.23,lng:32.55,t:"gold",note:"Narrow high-grade quartz veins in the Sukumaland greenstone belt."},
{n:"North Mara–Tarime",c:"Tanzania",lat:-1.35,lng:34.40,t:"gold",note:"Mara greenstone belt gold near the Kenyan border."},
{n:"Lupa Goldfield (Chunya)",c:"Tanzania",lat:-8.53,lng:33.42,t:"gold",note:"Historic 1930s goldfield; reef and alluvial workings still active artisanally."},
{n:"Sekenke District",c:"Tanzania",lat:-4.27,lng:34.17,t:"gold",note:"One of Tanzania's oldest gold mines (1909) and its surrounding belt."},
{n:"Merelani (Tanzanite)",c:"Tanzania",lat:-3.55,lng:36.98,t:"gem",note:"The only tanzanite locality on Earth, at the foot of Kilimanjaro."},
{n:"Mwadui (Williamson)",c:"Tanzania",lat:-3.55,lng:33.60,t:"gem",note:"Century-scale diamond pipe; the world's longest continuously mined kimberlite."},
/* ---------------- SOUTH AFRICA ---------------- */
{n:"Witwatersrand Basin",c:"South Africa",lat:-26.20,lng:28.05,t:"gold",note:"The most productive goldfield in history; conglomerate reef gold around Johannesburg."},
{n:"Free State Goldfields (Welkom)",c:"South Africa",lat:-27.98,lng:26.73,t:"gold",note:"Southern extension of the Wits; deep-level reef gold."},
{n:"Klerksdorp Goldfield",c:"South Africa",lat:-26.87,lng:26.67,t:"gold",note:"Western Wits goldfield; among the deepest mines on Earth."},
{n:"Barberton Belt",c:"South Africa",lat:-25.79,lng:31.05,t:"gold",note:"One of Earth's oldest greenstone belts; reef gold mined since the 1880s."},
{n:"Pilgrim's Rest–Sabie",c:"South Africa",lat:-24.89,lng:30.76,t:"gold",note:"Historic alluvial and reef goldfield on the Mpumalanga escarpment."},
{n:"Murchison Belt (Gravelotte)",c:"South Africa",lat:-23.95,lng:30.65,t:"gold",note:"Antimony–gold greenstone belt in Limpopo; long production history."},
{n:"Kalahari Manganese Field",c:"South Africa",lat:-27.15,lng:22.98,t:"metal",note:"The largest land-based manganese resource on Earth, around Hotazel."},
{n:"Steenkampskraal",c:"South Africa",lat:-31.00,lng:18.55,t:"ree",note:"Monazite vein with exceptionally high REE grade; historic thorium mine."},
/* ---------------- DR CONGO ---------------- */
{n:"Kibali District (Haut-Uélé)",c:"DR Congo",lat:3.05,lng:29.56,t:"gold",note:"Moto goldfields of the Kilo-Moto belt; a major modern producing district."},
{n:"Mongbwalu (Kilo Belt)",c:"DR Congo",lat:1.95,lng:30.05,t:"gold",note:"Ituri's historic Kilo goldfields; a century of production, heavily artisanal today."},
{n:"Twangiza Belt",c:"DR Congo",lat:-2.80,lng:28.78,t:"gold",note:"South Kivu gold belt of the Twangiza–Namoya trend."},
{n:"Kivu Tin–Tantalite Belt",c:"DR Congo",lat:-2.50,lng:28.85,t:"metal",note:"Pegmatite tin, tantalite and tungsten province of the Kibaran belt."},
{n:"Manono Pegmatite",c:"DR Congo",lat:-7.30,lng:27.42,t:"metal",note:"Giant lithium–tin pegmatite; historic tin, world-class lithium."},
{n:"Mbuji-Mayi Diamond Fields",c:"DR Congo",lat:-6.15,lng:23.60,t:"gem",note:"Kasai's vast industrial-diamond fields; alluvial and kimberlitic."},
/* ---------------- BURKINA FASO ---------------- */
{n:"Essakane District",c:"Burkina Faso",lat:14.39,lng:-0.02,t:"gold",note:"Sahel-zone Birimian gold; extensive artisanal history."},
{n:"Houndé Belt",c:"Burkina Faso",lat:11.50,lng:-3.52,t:"gold",note:"Birimian greenstone belt with multiple documented deposits."},
{n:"Poura District",c:"Burkina Faso",lat:11.60,lng:-2.75,t:"gold",note:"Burkina's historic gold mine and its surrounding Birimian ground."},
/* ---------------- CÔTE D'IVOIRE ---------------- */
{n:"Ity District",c:"Côte d'Ivoire",lat:6.87,lng:-8.09,t:"gold",note:"Western Birimian gold along the Cavally river; long alluvial history."},
{n:"Tongon District",c:"Côte d'Ivoire",lat:9.95,lng:-5.92,t:"gold",note:"Northern Côte d'Ivoire Birimian belt gold district."},
{n:"Yaouré District",c:"Côte d'Ivoire",lat:7.02,lng:-5.42,t:"gold",note:"Central Birimian gold near Lake Kossou; modern producing district."},
{n:"Séguéla District",c:"Côte d'Ivoire",lat:7.96,lng:-6.67,t:"gold",note:"Recent high-grade discovery district in the western Birimian."},
/* ---------------- GUINEA ---------------- */
{n:"Siguiri Basin",c:"Guinea",lat:11.42,lng:-9.17,t:"gold",note:"Alluvial and laterite gold worked for centuries — heart of the old Mali Empire trade."},
{n:"Lefa District",c:"Guinea",lat:11.68,lng:-9.30,t:"gold",note:"Laterite-hosted gold adjoining the Siguiri basin."},
{n:"Kouroussa District",c:"Guinea",lat:10.65,lng:-9.88,t:"gold",note:"Upper Niger Birimian gold; alluvial workings along the river."},
{n:"Banankoro Diamond Area",c:"Guinea",lat:9.20,lng:-9.05,t:"gem",note:"Guinea's alluvial diamond fields in the Kérouané region (area approximate)."},
/* ---------------- SENEGAL / GAMBIA / G-BISSAU ---------------- */
{n:"Sabodala District",c:"Senegal",lat:13.15,lng:-12.10,t:"gold",note:"Eastern Senegal Birimian belt; the country's principal gold district."},
{n:"Kédougou Corridor",c:"Senegal",lat:12.56,lng:-12.17,t:"gold",note:"Designated artisanal gold corridors of the Kédougou region."},
{n:"Sanyang Mineral Sands",c:"Gambia",lat:13.28,lng:-16.78,t:"metal",note:"Coastal zircon–ilmenite sands south of Banjul."},
{n:"Boé Bauxite Plateau",c:"Guinea-Bissau",lat:11.35,lng:-14.25,t:"metal",note:"Undeveloped bauxite plateaus of the Boé region."},
/* ---------------- SUDAN / EGYPT ---------------- */
{n:"Ariab District",c:"Sudan",lat:18.60,lng:35.40,t:"gold",note:"Red Sea Hills volcanogenic district; centre of Sudan's gold rush."},
{n:"Wadi Gabgaba",c:"Sudan",lat:21.00,lng:33.50,t:"gold",note:"Nubian desert gold worked since antiquity; large modern operations and artisanal fields."},
{n:"Sukari District",c:"Egypt",lat:24.95,lng:34.71,t:"gold",note:"Nubian Shield gold worked since Pharaonic times."},
{n:"Wadi Allaqi",c:"Egypt",lat:22.90,lng:33.50,t:"gold",note:"Ancient Egyptian gold region of the far south-east desert."},
{n:"Fawakhir (El Sid)",c:"Egypt",lat:26.02,lng:33.60,t:"gold",note:"Pharaonic gold workings on the ancient Qift–Quseir road."},
/* ---------------- ETHIOPIA / ERITREA ---------------- */
{n:"Adola Belt (Lega Dembi)",c:"Ethiopia",lat:5.71,lng:38.95,t:"gold",note:"Southern Ethiopian greenstone belt; primary and placer gold."},
{n:"Tulu Kapi District",c:"Ethiopia",lat:9.00,lng:35.60,t:"gold",note:"Western Ethiopian shield gold in Wollega."},
{n:"Kenticha Pegmatite",c:"Ethiopia",lat:5.58,lng:38.98,t:"metal",note:"Tantalum–lithium pegmatite field beside the Adola belt."},
{n:"Bisha District",c:"Eritrea",lat:15.50,lng:37.55,t:"gold",note:"VMS gold–copper–zinc district of the Eritrean Nubian Shield."},
/* ---------------- NIGERIA / NIGER / CHAD ---------------- */
{n:"Ilesha–Segilola Belt",c:"Nigeria",lat:7.60,lng:4.73,t:"gold",note:"South-western schist belt gold; Nigeria's principal modern gold district."},
{n:"Anka–Zamfara Goldfield",c:"Nigeria",lat:12.10,lng:5.92,t:"gold",note:"North-western goldfields; large artisanal sector, serious security risk."},
{n:"Jos Plateau Tin Field",c:"Nigeria",lat:9.93,lng:8.89,t:"metal",note:"Century-old tin and columbite field on the Jos Plateau."},
{n:"Samira Hill District",c:"Niger",lat:13.70,lng:1.60,t:"gold",note:"Liptako Birimian gold west of the Niger river."},
{n:"Djado Rush Zone",c:"Niger",lat:21.00,lng:12.30,t:"gold",note:"Remote Saharan detector rush; unregulated and dangerous."},
{n:"Arlit Uranium District",c:"Niger",lat:18.74,lng:7.39,t:"metal",note:"The Aïr uranium district mined since the 1970s."},
{n:"Miski Zone (Tibesti)",c:"Chad",lat:21.35,lng:17.35,t:"gold",note:"Tibesti artisanal gold zone; access restricted and hazardous."},
/* ---------------- CAMEROON / CAR / CONGO / GABON / EQ. GUINEA ---------------- */
{n:"Bétaré-Oya District",c:"Cameroon",lat:5.60,lng:14.08,t:"gold",note:"East Cameroon's principal alluvial gold district on the Lom river."},
{n:"Kadey–Batouri District",c:"Cameroon",lat:4.43,lng:14.36,t:"gold",note:"Alluvial gold drainages of the Kadey; active artisanal ground."},
{n:"Berbérati Diamond Fields",c:"Central African Republic",lat:4.26,lng:15.79,t:"gem",note:"Western CAR alluvial diamonds; hand-worked gravels."},
{n:"Bambari District",c:"Central African Republic",lat:5.77,lng:20.67,t:"gold",note:"Central CAR gold occurrences; artisanal and conflict-affected."},
{n:"Kellé Forest Gold",c:"Congo, Republic of",lat:0.00,lng:14.50,t:"gold",note:"Alluvial gold of the north-western forests."},
{n:"Zanaga Iron District",c:"Congo, Republic of",lat:-2.85,lng:13.83,t:"metal",note:"Large undeveloped iron formation of the Chaillu massif."},
{n:"Etéké Goldfield",c:"Gabon",lat:-1.47,lng:11.48,t:"gold",note:"Gabon's historic gold district in the Massif du Chaillu forests."},
{n:"Moanda Manganese",c:"Gabon",lat:-1.57,lng:13.20,t:"metal",note:"One of the world's great manganese plateaus."},
{n:"Aconibe Alluvials",c:"Equatorial Guinea",lat:1.30,lng:10.93,t:"gold",note:"Río Muni alluvial gold occurrences."},
/* ---------------- KENYA / UGANDA / RWANDA / BURUNDI / S.SUDAN / SOMALIA ---------------- */
{n:"Kakamega Goldfield",c:"Kenya",lat:0.28,lng:34.75,t:"gold",note:"Kenya's principal greenstone gold district; 1930s rush ground."},
{n:"Migori–Macalder Belt",c:"Kenya",lat:-1.00,lng:34.40,t:"gold",note:"Southern Nyanza greenstone gold near Lake Victoria."},
{n:"Taita Taveta Gem Fields",c:"Kenya",lat:-3.40,lng:38.35,t:"gem",note:"Tsavorite's home; licensed small-scale gemstone country."},
{n:"Busia Goldfield",c:"Uganda",lat:0.45,lng:34.05,t:"gold",note:"A century of gold on the Kenya border; Uganda's main gold district."},
{n:"Kilembe District",c:"Uganda",lat:0.20,lng:30.00,t:"metal",note:"Historic copper–cobalt mine at the Rwenzori foothills."},
{n:"Makuutu REE District",c:"Uganda",lat:0.60,lng:33.60,t:"ree",note:"Ionic-clay rare earths — the style that supplies most heavy REE."},
{n:"Gatumba Pegmatite Field",c:"Rwanda",lat:-1.92,lng:29.65,t:"metal",note:"Tantalum–tin pegmatites; Rwanda's 3T heartland."},
{n:"Miyove Gold Belt",c:"Rwanda",lat:-1.62,lng:30.08,t:"gold",note:"Northern Rwanda gold belt; formalised small-scale mining."},
{n:"Gakara REE District",c:"Burundi",lat:-3.55,lng:29.45,t:"ree",note:"Vein-hosted bastnäsite; among the highest-grade REE occurrences globally."},
{n:"Muyinga Gold Area",c:"Burundi",lat:-2.85,lng:30.34,t:"gold",note:"North-eastern Burundi artisanal gold."},
{n:"Kapoeta Goldfields",c:"South Sudan",lat:4.77,lng:33.59,t:"gold",note:"Eastern Equatoria alluvial gold; informal frontier."},
{n:"Borama Gem Area",c:"Somalia",lat:9.94,lng:43.18,t:"gem",note:"Somaliland emerald and sapphire occurrences (area approximate)."},
/* ---------------- ZAMBIA / MALAWI / MOZAMBIQUE ---------------- */
{n:"Copperbelt (Kitwe–Chingola)",c:"Zambia",lat:-12.80,lng:28.21,t:"metal",note:"World-class sediment-hosted copper–cobalt province."},
{n:"Kansanshi District",c:"Zambia",lat:-12.10,lng:26.43,t:"metal",note:"Copper–gold district in North-Western Province."},
{n:"Kagem Emerald District",c:"Zambia",lat:-13.05,lng:28.05,t:"gem",note:"Kafubu emerald fields; major world emerald source."},
{n:"Mumbwa–Dunrobin District",c:"Zambia",lat:-15.00,lng:27.05,t:"gold",note:"Central Zambia's historic gold camp."},
{n:"Mwinilunga (Kasenseli)",c:"Zambia",lat:-11.73,lng:24.43,t:"gold",note:"North-western Zambia's new gold frontier."},
{n:"Kangankunde Carbonatite",c:"Malawi",lat:-15.55,lng:34.85,t:"ree",note:"One of the world's highest-grade rare earth carbonatites."},
{n:"Songwe Hill",c:"Malawi",lat:-15.85,lng:35.55,t:"ree",note:"Carbonatite-hosted rare earth district in the Chilwa province."},
{n:"Kasiya Rutile District",c:"Malawi",lat:-13.80,lng:33.55,t:"metal",note:"The largest known natural rutile deposit on Earth."},
{n:"Manica Goldfield",c:"Mozambique",lat:-18.94,lng:32.87,t:"gold",note:"Mozambique's artisanal gold heart, continuous with Zimbabwe's Penhalonga."},
{n:"Montepuez Ruby District",c:"Mozambique",lat:-13.13,lng:39.00,t:"gem",note:"The world's most significant ruby district, discovered 2009."},
{n:"Alto Ligonha Pegmatites",c:"Mozambique",lat:-15.50,lng:38.30,t:"metal",note:"Classic tantalite, beryl and gemstone pegmatite field."},
/* ---------------- NAMIBIA / BOTSWANA / ANGOLA / LESOTHO / ESWATINI ---------------- */
{n:"Erongo Tin Belt",c:"Namibia",lat:-21.65,lng:15.65,t:"metal",note:"Pegmatite tin and tantalite with world-famous mineral specimens."},
{n:"Erongo Gem Fields",c:"Namibia",lat:-21.60,lng:15.72,t:"gem",note:"Aquamarine, tourmaline and topaz from granite pegmatites."},
{n:"Lofdal Heavy REE District",c:"Namibia",lat:-20.35,lng:14.75,t:"ree",note:"Rare heavy-REE (dysprosium) enriched carbonatite dykes near Khorixas."},
{n:"Rehoboth Gold Area",c:"Namibia",lat:-23.32,lng:17.08,t:"gold",note:"Historic small gold workings of the Rehoboth basement."},
{n:"Sperrgebiet Diamond Coast",c:"Namibia",lat:-27.60,lng:15.65,t:"gem",note:"The forbidden diamond coast — strictly licensed, shown for the record."},
{n:"Tati Belt (Francistown)",c:"Botswana",lat:-21.17,lng:27.51,t:"gold",note:"Botswana's historic gold belt; the 1869 rush that predated the Rand."},
{n:"Orapa Kimberlite Field",c:"Botswana",lat:-21.31,lng:25.37,t:"gem",note:"One of the world's great diamond pipes."},
{n:"Jwaneng Kimberlite",c:"Botswana",lat:-24.60,lng:24.72,t:"gem",note:"The richest diamond mine on Earth by value."},
{n:"Catoca Kimberlite",c:"Angola",lat:-9.40,lng:20.30,t:"gem",note:"Among the world's largest kimberlite mines, Lunda Sul."},
{n:"Chipindo Gold Area",c:"Angola",lat:-13.85,lng:15.78,t:"gold",note:"Huíla's gold district; artisanal and modern exploration."},
{n:"Cassinga Iron District",c:"Angola",lat:-15.12,lng:16.05,t:"metal",note:"Angola's historic iron mining district."},
{n:"Letšeng Kimberlites",c:"Lesotho",lat:-29.00,lng:28.72,t:"gem",note:"The highest-value diamonds per carat on Earth, above 3,000 m."},
{n:"Ngwenya (Historic)",c:"Eswatini",lat:-26.20,lng:31.03,t:"metal",note:"The oldest known mine on Earth (~40,000 years); heritage site, not a digging site."},
/* ---------------- MAURITANIA / MOROCCO / ALGERIA / TUNISIA / LIBERIA / SIERRA LEONE / BENIN / MADAGASCAR ---------------- */
{n:"Tasiast District",c:"Mauritania",lat:20.53,lng:-15.50,t:"gold",note:"Archean belt gold of the Reguibat Shield."},
{n:"Chami Artisanal Zone",c:"Mauritania",lat:20.05,lng:-15.95,t:"gold",note:"The legal detector-prospecting zone that drew tens of thousands."},
{n:"Akjoujt Copper–Gold",c:"Mauritania",lat:19.75,lng:-14.38,t:"metal",note:"Inchiri copper–gold district; historic and modern mining."},
{n:"Imiter Silver District",c:"Morocco",lat:31.30,lng:-5.70,t:"metal",note:"One of Africa's great silver mines, worked since the 8th century."},
{n:"Bou Azzer Cobalt District",c:"Morocco",lat:30.52,lng:-6.90,t:"metal",note:"The world's only primary cobalt district; famed mineral specimens."},
{n:"Tirek–Amesmessa",c:"Algeria",lat:21.05,lng:2.50,t:"gold",note:"Hoggar shear-zone gold of the deep Sahara."},
{n:"Gara Djebilet Iron",c:"Algeria",lat:26.70,lng:-7.40,t:"metal",note:"Giant oolitic iron deposit of the Tindouf basin."},
{n:"Gafsa Phosphate Basin",c:"Tunisia",lat:34.42,lng:8.78,t:"metal",note:"Tunisia's century-old phosphate mining basin."},
{n:"Kokoya District",c:"Liberia",lat:6.85,lng:-9.55,t:"gold",note:"Bong county gold; modern mining on old artisanal ground."},
{n:"Lofa Diamond Fields",c:"Liberia",lat:8.00,lng:-10.05,t:"gem",note:"North-western alluvial diamonds and gold."},
{n:"Kono Diamond Fields",c:"Sierra Leone",lat:8.65,lng:-10.97,t:"gem",note:"The famous hand-worked gravels; source of the 709-carat Peace Diamond."},
{n:"Sula Mountains Belt",c:"Sierra Leone",lat:9.05,lng:-11.60,t:"gold",note:"Greenstone gold belt of central Sierra Leone."},
{n:"Baomahun District",c:"Sierra Leone",lat:8.30,lng:-11.70,t:"gold",note:"Shear-hosted gold in the Kangari hills."},
{n:"Perma Goldfield",c:"Benin",lat:10.25,lng:1.35,t:"gold",note:"Atacora alluvial gold near Natitingou."},
{n:"Ilakaka Sapphire Fields",c:"Madagascar",lat:-22.68,lng:45.20,t:"gem",note:"Alluvial sapphire fields discovered 1998; among the largest on Earth."},
{n:"Andilamena Ruby Fields",c:"Madagascar",lat:-17.02,lng:48.58,t:"gem",note:"Forest ruby rush ground of eastern Madagascar."},
{n:"Maevatanana Goldfield",c:"Madagascar",lat:-16.95,lng:46.83,t:"gold",note:"Madagascar's principal historic goldfield."},
{n:"Betsiaka Gold Area",c:"Madagascar",lat:-13.15,lng:49.25,t:"gold",note:"Northern alluvial gold; long artisanal history."},
{n:"Ambatovy District",c:"Madagascar",lat:-18.85,lng:48.30,t:"metal",note:"Major lateritic nickel–cobalt district."}
];

/* ---- Map view per country: [lat, lng, zoom] ---- */
const COUNTRY_VIEWS={
"Algeria":[28,2.5,5],"Angola":[-12.5,17.5,5],"Benin":[9.5,2.3,6],"Botswana":[-22.3,24,5],
"Burkina Faso":[12.3,-1.7,6],"Burundi":[-3.4,29.9,8],"Cabo Verde":[15.1,-23.6,7],
"Cameroon":[5.7,12.7,5],"Central African Republic":[6.6,20.5,5],"Chad":[15.5,18.7,5],
"Comoros":[-11.9,43.9,8],"Congo, Republic of":[-0.7,15.2,6],"DR Congo":[-3,23,5],
"Côte d'Ivoire":[7.6,-5.5,6],"Djibouti":[11.8,42.6,8],"Egypt":[26.5,30,5],
"Equatorial Guinea":[1.6,10.4,7],"Eritrea":[15.2,38.9,6],"Eswatini":[-26.5,31.4,8],
"Ethiopia":[8.6,39.6,5],"Gabon":[-0.6,11.7,6],"Gambia":[13.4,-15.4,7],"Ghana":[7.9,-1.2,6],
"Guinea":[10.4,-10.9,6],"Guinea-Bissau":[12,-15,7],"Kenya":[0.4,37.8,5],"Lesotho":[-29.6,28.2,7],
"Liberia":[6.4,-9.4,6],"Libya":[27,17,5],"Madagascar":[-19,46.8,5],"Malawi":[-13.3,34.3,6],
"Mali":[15,-6,5],"Mauritania":[20.3,-10.5,5],"Mauritius":[-20.3,57.55,9],"Morocco":[31.8,-6.5,5],
"Mozambique":[-17.5,35.5,5],"Namibia":[-22.5,17,5],"Niger":[17.5,8.5,5],"Nigeria":[9.1,8,5],
"Rwanda":[-2,29.9,8],"São Tomé & Príncipe":[0.25,6.6,9],"Senegal":[14.4,-14.3,6],
"Seychelles":[-4.7,55.5,9],"Sierra Leone":[8.5,-11.8,7],"Somalia":[6,46,5],
"South Africa":[-29,25,5],"South Sudan":[7.3,30.2,5],"Sudan":[15.5,30,5],"Tanzania":[-6.4,35,5],
"Togo":[8.6,1,6],"Tunisia":[34,9.5,6],"Uganda":[1.3,32.3,6],"Zambia":[-13.5,28,5],
"Zimbabwe":[-19,29.8,6]};

const COUNTRIES=[
{n:"Algeria",b:"HOGGAR SHIELD",min:"Gold, iron, zinc, phosphate, barite",mines:"Amesmessa & Tirek gold (Hoggar), Gara Djebilet iron, Oued Amizour zinc",cos:"Sonarem (state), ENOR",law:"Mining Law of 2014; permits via the National Agency for Mining Activities (ANAM). The state dominates the sector and foreign participation is tightly framed.",tip:"The Saharan gold country is remote and state-controlled — independent prospecting is heavily restricted."},
{n:"Angola",b:"LUNDA CRATON",min:"Diamonds, gold, iron, phosphate",mines:"Catoca & Luele diamonds (Lunda Sul), Chipindo gold (Huíla), Cassinga iron",cos:"Endiama (state), Sociedade Mineira de Catoca",law:"Mining Code (Law 31/11); licences via the Ministry of Mineral Resources; the diamond trade is tightly controlled end to end.",tip:"Alluvial diamond areas are restricted zones — never enter without written authorisation."},
{n:"Benin",b:"ATACORA",min:"Gold, phosphate, limestone",mines:"Perma goldfield (Natitingou), Alibori artisanal zones",cos:"Mostly artisanal operators",law:"Mining Code of 2006; Ministry of Water and Mines issues permits.",tip:"A small artisanal gold country — the Perma river gravels are the documented target."},
{n:"Botswana",b:"KALAHARI / KAAPVAAL MARGIN",min:"Diamonds (world #1 by value), copper, nickel, coal, soda ash",mines:"Jwaneng & Orapa (among the richest diamond mines on Earth), Khoemacau copper",cos:"Debswana (De Beers + Government), MMG",law:"Mines and Minerals Act 1999; Department of Mines. Transparent licensing and low corruption by regional standards.",tip:"Diamonds are firmly state-partnered; the Kalahari Copper Belt is the modern exploration hotspot."},
{n:"Burkina Faso",b:"BIRIMIAN BELTS",min:"Gold (~60 t/yr), zinc, manganese",mines:"Essakane, Houndé, Sanbrado gold; Perkoa zinc",cos:"IAMGOLD, Endeavour Mining, West African Resources",law:"Mining Code 2015 with 2024 revisions raising state participation; ANEEMAS oversees the artisanal sector.",tip:"Major gold nation, but serious security risks in the north and east — check current travel guidance first."},
{n:"Burundi",b:"KIBARAN BELT",min:"Gold, rare earths, nickel, tin",mines:"Gakara REE veins, Muyinga & Cibitoke gold, Musongati nickel",cos:"Rainbow Rare Earths (Gakara, suspended), artisanal co-operatives",law:"Mining Code 2013 (revised 2023); exports are channelled through the state.",tip:"Gold is largely artisanal and export rules change often — verify the current legal channel before trading."},
{n:"Cabo Verde",b:"VOLCANIC ISLANDS",min:"Pozzolana, salt, limestone — no metallic mining",mines:"Salt pans of Sal and Maio",cos:"—",law:"Quarrying permits via the industry directorate.",tip:"Not a prospecting destination; included for completeness."},
{n:"Cameroon",b:"ADAMAWA / EAST",min:"Gold, bauxite, iron, cobalt-nickel",mines:"Bétaré-Oya & Colomines gold (East), Minim-Martap bauxite, Mbalam iron",cos:"Sonamines (state), Canyon Resources",law:"Mining Code 2016; Sonamines carries state interests; artisanal permits exist for nationals.",tip:"East-region alluvial gold is very active — the Kadey and Lom drainages are the documented ground."},
{n:"Central African Republic",b:"ALLUVIAL FIELDS",min:"Diamonds, gold",mines:"Berbérati & Carnot diamond fields, Bambari gold",cos:"Artisanal sector",law:"Mining Code 2009; Kimberley Process restrictions still apply to some zones.",tip:"A high-risk jurisdiction; parts of the diamond trade remain under international restriction."},
{n:"Chad",b:"TIBESTI / BATHA",min:"Gold, natron, salt",mines:"Miski & Kouri Bougoudi gold zones (Tibesti), Batha artisanal areas",cos:"Artisanal operators",law:"Mining Code 2018; Ministry of Mines and Geology.",tip:"The Saharan gold zones are military-sensitive — access is restricted and dangerous."},
{n:"Comoros",b:"VOLCANIC ISLANDS",min:"No commercial mining (sand, aggregates)",mines:"—",cos:"—",law:"—",tip:"Not a prospecting destination; included for completeness."},
{n:"Congo, Republic of",b:"MAYOMBE / KOUILOU",min:"Potash, iron, gold, copper",mines:"Kola & Dougou potash, Zanaga iron, Kellé artisanal gold",cos:"Kore Potash, state interests",law:"Mining Code 2005; Ministry of Mines and Geology.",tip:"Artisanal gold occurs in the Sangha and Kellé forests; logistics are the main barrier."},
{n:"Côte d'Ivoire",b:"BIRIMIAN BELTS",min:"Gold (~50 t/yr and rising), manganese, nickel",mines:"Ity, Tongon, Yaouré, Séguéla gold; Bondoukou manganese",cos:"Endeavour, Barrick, Perseus, Fortuna",law:"Mining Code 2014; SODEMI is the state geology company; artisanal authorisations exist for nationals.",tip:"One of Africa's fastest-growing gold producers; the west (Cavally basin) has centuries of alluvial history."},
{n:"DR Congo",b:"KATANGA / KILO-MOTO / KIVU",min:"Copper, cobalt (~70% of world supply), gold, tin, tantalite, diamonds",mines:"Kamoa-Kakula & Tenke copper, Kibali gold, Bisie tin, Mbuji-Mayi diamonds",cos:"Ivanhoe, Barrick, Glencore, CMOC, Alphamin, Gécamines (state)",law:"Mining Code 2018 (higher royalties; cobalt is a 'strategic' mineral at 10%); the CAMI cadastre is online. Artisanal work is legal only inside designated ZEA zones.",tip:"Working outside a ZEA or on someone's permit is a crime, and conflict-mineral traceability rules apply to tin and tantalite exports."},
{n:"Djibouti",b:"AFAR TRIANGLE",min:"Salt (Lake Assal), perlite, gypsum; early gold exploration",mines:"Lake Assal salt flats",cos:"Salt Investment",law:"Ministry of Energy and Natural Resources.",tip:"Geothermal and salt country; metallic prospecting is embryonic."},
{n:"Egypt",b:"NUBIAN SHIELD",min:"Gold (~20 t/yr), phosphate, tantalum, ilmenite",mines:"Sukari (Eastern Desert), Hamash & Abu Marawat gold, Abu Dabbab tantalum",cos:"AngloGold Ashanti (Sukari), Aton Resources",law:"Mineral Resources Law as amended in 2020 moved to a royalty/tax model; EMRA runs licensing rounds for Eastern Desert blocks.",tip:"The Eastern Desert holds over a hundred ancient Pharaonic gold workings — the modern districts follow them."},
{n:"Equatorial Guinea",b:"RÍO MUNI",min:"Alluvial gold; exploration-stage iron and bauxite",mines:"Coro & Aconibe artisanal gold",cos:"—",law:"Mining Law 2006; Ministry of Mines.",tip:"A small alluvial scene in the mainland rivers."},
{n:"Eritrea",b:"NUBIAN SHIELD (VMS)",min:"Gold, copper, zinc, potash",mines:"Bisha (gold-copper-zinc), Zara/Koka gold, Colluli potash",cos:"Zijin Mining (Bisha), ENAMCO (state)",law:"Mining Proclamation 1995; the state takes 10% free plus a 30% paid interest in mines.",tip:"There is no independent artisanal prospecting — the state controls all mineral activity."},
{n:"Eswatini",b:"BARBERTON EDGE",min:"Coal, quarry stone; historic iron and gold",mines:"Ngwenya (the oldest known mine on Earth, worked ~40,000 years ago), Maloma coal",cos:"—",law:"Minerals sit in trust with the Crown; Mines and Minerals Act 2011.",tip:"Ngwenya is a heritage site — a place to visit, not to dig."},
{n:"Ethiopia",b:"ADOLA / WESTERN SHIELD",min:"Gold, tantalum, opal, potash, lithium",mines:"Lega Dembi & Sakaro gold, Kenticha tantalum-lithium, Wollo opal fields, Danakil potash",cos:"MIDROC, Kefi Gold (Tulu Kapi)",law:"Mining Proclamation 678/2010 as amended; artisanal licences are issued by regional bureaus.",tip:"Over a million artisanal miners work here; Oromia and Benishangul are the gold regions — check regional security first."},
{n:"Gabon",b:"OGOOUÉ BASIN",min:"Manganese (world #2), gold, iron",mines:"Moanda manganese, Etéké & Ndjolé gold, Belinga iron",cos:"Comilog/Eramet, state SEM",law:"Mining Code 2019; the state holds a 10% free carry; Ministry of Mines issues permits.",tip:"Rainforest logistics rule everything; gold is alluvial in the Ogooué tributaries."},
{n:"Gambia",b:"COASTAL SANDS",min:"Zircon, ilmenite, rutile (mineral sands)",mines:"Batukunku–Sanyang beach sands",cos:"GACH",law:"Mines and Quarries Act; Geology Department.",tip:"Beach-sand country — there is no gold story here."},
{n:"Ghana",b:"ASHANTI / SEFWI / BIRIM",min:"Gold (Africa's #1 producer, roughly 4 Moz/yr), manganese, bauxite, diamonds, lithium",mines:"Obuasi, Tarkwa, Ahafo, Damang gold; Nsuta manganese; Akwatia diamonds; Ewoyaa lithium",cos:"AngloGold Ashanti, Gold Fields, Newmont",law:"Minerals and Mining Act 2006 (Act 703); the Minerals Commission cadastre is online. Small-scale licences are reserved for Ghanaian citizens, and unlicensed 'galamsey' mining is a criminal offence.",tip:"The most mature gold industry in Africa — but foreigners cannot hold small-scale licences, so partner legally."},
{n:"Guinea",b:"BOKÉ / SIGUIRI / SIMANDOU",min:"Bauxite (the world's top exporter), gold, iron, diamonds",mines:"Sangarédi bauxite, Siguiri & Lefa gold, Simandou iron (the largest untapped iron deposit on Earth), Banankoro diamonds",cos:"CBG, SMB-Winning, AngloGold Ashanti, Nordgold, Rio Tinto",law:"Mining Code 2011 as amended 2013; the state holds a 15% free carry; artisanal gold moves through licensed comptoirs.",tip:"The Siguiri basin's alluvial gold has been worked since the Mali Empire — this is Mansa Musa country."},
{n:"Guinea-Bissau",b:"BOÉ PLATEAU",min:"Bauxite (undeveloped), phosphate, heavy sands",mines:"Boé bauxite, Farim phosphate",cos:"GB Minerals",law:"Mining Code 2014.",tip:"A frontier jurisdiction with nothing yet in production."},
{n:"Kenya",b:"NYANZA / MOZAMBIQUE BELT",min:"Titanium sands, gold, fluorspar, soda ash, gemstones (tsavorite)",mines:"Kwale mineral sands, Kakamega–Migori gold, Taita Taveta gemstone fields, Lake Magadi soda",cos:"Base Titanium, Shanta Gold",law:"Mining Act 2016 with an online cadastre portal; artisanal permits for citizens.",tip:"Tsavorite garnet was discovered here — Taita Taveta is licensed small-scale gemstone country."},
{n:"Lesotho",b:"KIMBERLITE HIGHLANDS",min:"Diamonds — famous for huge, high-value stones",mines:"Letšeng (highest average value per carat on Earth), Kao, Liqhobong, Mothae",cos:"Gem Diamonds, Namakwa, Lucapa",law:"Mines and Minerals Act 2005; Commissioner of Mines.",tip:"Letšeng has produced multiple 500+ carat diamonds from kimberlites above 3,000 m altitude."},
{n:"Liberia",b:"ARCHEAN NIMBA",min:"Iron, gold, diamonds",mines:"Nimba iron, New Liberty & Kokoya gold, Lofa diamonds",cos:"ArcelorMittal, Avesoro, MNG Gold",law:"Minerals and Mining Law 2000; Class C artisanal licences are reserved for Liberians.",tip:"Alluvial gold and diamonds run across Lofa, Gbarpolu and Grand Cape Mount — Class C areas are mapped by the Ministry."},
{n:"Libya",b:"SAHARAN PLATFORM",min:"Iron (undeveloped), gypsum, salt; artisanal gold in the far south",mines:"Wadi ash-Shati iron, Tibesti-fringe gold",cos:"—",law:"Framework in flux.",tip:"Not currently a safe or licensed prospecting destination."},
{n:"Madagascar",b:"PRECAMBRIAN MOSAIC",min:"Sapphires & rubies, nickel, cobalt, ilmenite, graphite, gold, rare earths",mines:"Ilakaka sapphires, Ambatovy nickel-cobalt, QMM ilmenite, Andilamena rubies, Molo graphite",cos:"Ambatovy consortium, Rio Tinto QMM, NextSource",law:"Mining Code revised 2023 with higher royalties; the BCMM cadastre issues permits; gold exports run through a central channel.",tip:"Ilakaka is the world's great open sapphire rush — a licensed local partnership is essential."},
{n:"Malawi",b:"CHILWA CARBONATITES",min:"Rare earths, rutile, niobium, uranium, gemstones",mines:"Kangankunde & Songwe Hill REE, Kasiya rutile (the largest known rutile deposit), Kayelekera uranium, Kanyika niobium",cos:"Lindian, Mkango, Sovereign Metals, Lotus",law:"Mines and Minerals Act 2023; a new mining authority is being stood up.",tip:"Southern Africa's coming rare-earth country; Mzimba also hosts artisanal gemstones."},
{n:"Mali",b:"KÉNIÉBA / SOUTHERN BIRIMIAN",min:"Gold (~65 t/yr — Africa's top four), lithium, iron",mines:"Loulo-Gounkoto, Fekola, Sadiola, Syama, Morila gold; Goulamina lithium",cos:"Barrick, B2Gold, Allied Gold, Resolute, Ganfeng",law:"Mining Code 2023: combined state and local participation can reach ~35%, and old stability clauses were removed. The DNGM administers titles, and artisanal corridors are designated.",tip:"An enormous artisanal sector works alongside the majors; security varies sharply by region — Kéniéba in the west is the historic heart."},
{n:"Mauritania",b:"REGUIBAT SHIELD",min:"Iron, gold, copper, gypsum",mines:"Zouérat iron (SNIM's ore trains run ~2.5 km long), Tasiast gold, Guelb Moghrein copper-gold; Inchiri artisanal zones",cos:"SNIM, Kinross",law:"Mining Code 2008 as amended. Artisanal gold was legalised in 2016 in designated zones administered from Chami.",tip:"The Chami zone drew tens of thousands of detectorists — one of the world's few legal detector gold rushes."},
{n:"Mauritius",b:"VOLCANIC ISLAND",min:"No metallic mining (basalt, sand)",mines:"—",cos:"—",law:"—",tip:"Not a prospecting destination."},
{n:"Morocco",b:"ANTI-ATLAS / MESETA",min:"Phosphate (the world's largest reserves), silver, cobalt, zinc, copper, barite",mines:"Khouribga & Benguérir phosphate, Imiter silver, Bou Azzer cobalt, Drâa copper belt",cos:"OCP (state phosphate giant), Managem",law:"Mining Code 2015 (Law 33-13); ONHYM handles geology; regional directorates issue permits.",tip:"The Anti-Atlas is a mineral collector's paradise — specimen digging (azurite, vanadinite) is its own licensed trade."},
{n:"Mozambique",b:"MONTEPUEZ / ALTO LIGONHA / TETE",min:"Rubies (world #1), graphite, heavy sands, coal, gold, tantalite",mines:"Montepuez rubies, Balama graphite, Moma sands, Moatize coal, Manica gold",cos:"Gemfields, Syrah, Kenmare, Vulcan",law:"Mining Law 2014; the INAMI cadastre is online; the senha mineira artisanal pass is for nationals.",tip:"Manica province is the artisanal gold heart; the Cabo Delgado ruby country carries security restrictions."},
{n:"Namibia",b:"DAMARA BELT / NAMIB",min:"Uranium (world top three), marine diamonds, gold, tin, lithium, rare earths, gemstones",mines:"Husab & Rössing uranium, Debmarine offshore diamonds, Otjikoto gold, Uis tin, Lofdal REE, Erongo gem fields",cos:"CGN/CNNC, De Beers–Namdeb, B2Gold, Andrada",law:"Minerals (Prospecting and Mining) Act 1992; EPL licences via an online cadastre; non-diamond gemstone digging is licensable.",tip:"One of Africa's best-run mining registries — and Erongo is legendary for aquamarine and tourmaline."},
{n:"Niger",b:"LIPTAKO / AÏR",min:"Uranium, gold, coal, gypsum",mines:"Arlit uranium, Samira Hill gold, Djado & Aïr artisanal gold rushes",cos:"Orano (status disputed since 2024), SOPAMIN (state)",law:"Mining Code 2006 with 2024 revisions; foreign permits have been under review since the change of government.",tip:"The Djado rush drew thousands of Saharan detectorists — but the zone is remote, unregulated and dangerous."},
{n:"Nigeria",b:"SCHIST BELTS / JOS PLATEAU",min:"Gold, tin, columbite, lead-zinc, lithium, barite",mines:"Segilola gold (Osun), Zamfara & Kebbi goldfields, Jos Plateau tin, Ebonyi lead-zinc, Nasarawa lithium",cos:"Thor Explorations, artisanal co-operatives",law:"Nigerian Minerals and Mining Act 2007; the Mining Cadastre Office is online and small-scale leases are available. Zamfara's gold zones have faced periodic bans over banditry.",tip:"A huge artisanal sector; the north-west carries severe security risk — the south-west (Osun, Kwara) is the safer documented ground."},
{n:"Rwanda",b:"KIBARAN 3T BELT",min:"Tin, tantalum (a leading world exporter), tungsten, gold, gemstones",mines:"Rutongo tin, Gatumba tantalum pegmatites, Nyakabingo tungsten, Miyove gold",cos:"Trinity Metals, LuNa Smelter",law:"Mining Law 2018; Rwanda Mines Board; iTSCi traceability tagging is mandatory for tin/tantalum/tungsten exports.",tip:"A clean, formalised small-mining sector — but every kilo of 3T ore must be tagged and traceable."},
{n:"São Tomé & Príncipe",b:"VOLCANIC ISLANDS",min:"No mining",mines:"—",cos:"—",law:"—",tip:"Not a prospecting destination."},
{n:"Senegal",b:"KÉDOUGOU-KÉNIÉBA",min:"Gold, zircon, phosphate, ilmenite",mines:"Sabodala-Massawa gold, Mako gold, Grande Côte mineral sands, Matam phosphate",cos:"Endeavour, Managem, Eramet GCO",law:"Mining Code 2016; designated artisanal corridors (couloirs d'orpaillage) operate in Kédougou.",tip:"Kédougou is the legal artisanal gold region — the geology runs straight across the border into Mali's Kéniéba window."},
{n:"Seychelles",b:"GRANITE ISLANDS",min:"No mining (historic guano)",mines:"—",cos:"—",law:"—",tip:"Not a prospecting destination."},
{n:"Sierra Leone",b:"KONO / SULA MOUNTAINS",min:"Diamonds, rutile (world-class), iron, gold, bauxite",mines:"Kono & Tongo diamond fields, Sierra Rutile, Marampa & Tonkolili iron, Baomahun gold",cos:"Leone Rock, Sierra Rutile, FG Gold",law:"Mines and Minerals Development Act 2022; the National Minerals Agency licenses artisanal diamond digging for citizens.",tip:"Kono's gravels are still hand-worked — the 709-carat 'Peace Diamond' came from a village dig in 2017."},
{n:"Somalia",b:"NORTHERN BASEMENT",min:"Gemstones (sapphire, emerald in Somaliland), historic tin, salt, meerschaum",mines:"Simodi/Borama gem occurrences, Majayahan tin",cos:"Artisanal only",law:"The federal framework is nascent; Somaliland licenses separately.",tip:"An effectively unregulated frontier — not currently practical for visiting prospectors."},
{n:"South Africa",b:"WITWATERSRAND / BUSHVELD",min:"Gold, platinum (~70% of world PGMs), diamonds, chrome, manganese, coal, iron, vanadium",mines:"Witwatersrand gold mines (the deepest on Earth, ~4 km), the Bushveld platinum belt, Venetia & Cullinan diamonds, the Kalahari manganese field (the world's largest)",cos:"Sibanye-Stillwater, Harmony, Anglo American Platinum, Impala, De Beers, Petra",law:"MPRDA 2002; the DMRE issues rights via SAMRAD. Unlicensed mining (zama-zama) is heavily policed and lethally dangerous.",tip:"The public diggings era is over — but registered gem and mineral clubs run legal fossicking trips."},
{n:"South Sudan",b:"KAPOETA GREENSTONES",min:"Gold (artisanal), copper indications",mines:"Kapoeta & Nanaknak alluvial fields (Eastern Equatoria)",cos:"Artisanal",law:"Mining Act 2012; Ministry of Mining.",tip:"Almost entirely artisanal and informal; a high-risk frontier."},
{n:"Sudan",b:"NUBIAN SHIELD / RED SEA HILLS",min:"Gold (among Africa's top three including artisanal output), chrome, iron",mines:"Ariab district, Gabgaba, North Kordofan fields",cos:"Managem (Gabgaba), Sudanese Mineral Resources Co. (state)",law:"State channels gold purchases; the conflict since 2023 has pushed much of the sector informal.",tip:"Perhaps two million artisanal miners — but the ongoing war makes this a no-go for outside prospectors."},
{n:"Tanzania",b:"LAKE VICTORIA / MERELANI",min:"Gold (~50 t/yr), tanzanite (the only source on Earth), diamonds, graphite, nickel, coloured gemstones",mines:"Geita, Bulyanhulu, North Mara gold; Merelani tanzanite; Williamson diamonds; Kabanga nickel",cos:"AngloGold Ashanti, Barrick, Petra, Lifezone",law:"Mining Act 2010 with 2017 amendments: a 16% state free carry and local-content rules. Primary Mining Licences are reserved for Tanzanian citizens; the Mirerani gem trade is formalised.",tip:"Foreigners can't hold small-scale licences — joint ventures with PML holders are the legal route."},
{n:"Togo",b:"DAHOMEYIDE BELT",min:"Phosphate, iron, artisanal gold, manganese",mines:"Hahotoé-Kpogamé phosphate, Bangeli iron, Wawa artisanal gold",cos:"SNPT (state phosphate)",law:"Mining Code 1996, revised 2003.",tip:"A small artisanal gold scene along the Ghana-border rivers."},
{n:"Tunisia",b:"GAFSA BASIN",min:"Phosphate, zinc, lead, salt, iron",mines:"Gafsa phosphate basin, Bougrine zinc-lead",cos:"CPG-GCT (state)",law:"Mining Code 2003.",tip:"Phosphate country — there is no gold story."},
{n:"Uganda",b:"BUSIA / KARAMOJA",min:"Gold, rare earths, tin, historic copper-cobalt, phosphate, vermiculite",mines:"Busia goldfields (Wagagai), Karamoja artisanal gold, Makuutu ionic REE, Ntungamo tin, Kilembe copper (historic)",cos:"Wagagai Mining, Ionic Rare Earths",law:"Mining and Minerals Act 2022 introduced 15% state participation and formal artisanal permits.",tip:"Busia has a century of gold history; the Karamoja digs are informal and remote."},
{n:"Zambia",b:"COPPERBELT / KAFUBU",min:"Copper (Africa's #2), cobalt, world-class emeralds, gold, manganese, nickel",mines:"Kansanshi, Sentinel, Mopani, Konkola copper; Kagem emeralds; Kasenseli gold",cos:"First Quantum, Gemfields, ZCCM-IH (state)",law:"Mines and Minerals Development Act 2015; an online cadastre; artisanal and small-scale licences are available to citizens.",tip:"The Kafubu emerald fields feed world auctions; gold is the new frontier in North-Western Province."},
{n:"Zimbabwe",b:"GREENSTONE BELTS / GREAT DYKE",min:"Gold, platinum, chrome, lithium (Africa's #1), diamonds, nickel, tantalite",mines:"Blanket & Freda Rebecca gold; Zimplats, Unki & Mimosa platinum; Bikita & Arcadia lithium; Marange diamonds",cos:"Caledonia, Kuvimba, Implats, Sinomine, ZCDC",law:"Mines and Minerals Act (Chapter 21:05); a prospecting licence is issued by the Ministry of Mines for a modest fee. ALL gold must legally be sold to Fidelity Gold Refinery, and riverbed alluvial mining has been banned since 2021.",tip:"Over 4,000 recorded gold workings — more documented small mines than any country in Africa. Your home advantage."}
];
